inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# --- Metrics ---

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# because this isn't 1994
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

# --- Rails ---

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # because we're using touch on purpose

# --- RSpec ---

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 2

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

# --- Style ---

Style/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop ] isn't a big deal
