# This configuration was edited manually on 2018-08-13 while using RuboCop version 0.58.2.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/lib/okcomputer_spec.rb'
    - 'spec/models/complete_moab_spec.rb'
    - 'spec/models/druid_version_zip_part_spec.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines, beginning_only, ending_only
Layout/EmptyLinesAroundClassBody:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/services/audit_results.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: aligned, indented, indented_relative_to_receiver
Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/lib/preservation_catalog/s3/audit_spec.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: space, no_space
Layout/SpaceAroundEqualsInParameterDefault:
  Exclude:
    - 'app/lib/audit/checksum.rb'
    - 'app/services/audit_results.rb'
    - 'app/services/preserved_object_handler.rb'

# Offense count: 31
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/services/preserved_object_handler_check_exist_spec.rb'
    - 'spec/services/preserved_object_handler_confirm_version_spec.rb'
    - 'spec/services/preserved_object_handler_update_version_spec.rb'
    - 'spec/services/shared_examples_preserved_object_handler.rb'

# Offense count: 20
Metrics/AbcSize:
  Max: 71

# Offense count: 2
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 4

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 262

# Offense count: 3
Metrics/CyclomaticComplexity:
  Max: 11

# Offense count: 5
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 205

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Exclude:
    - 'app/services/preserved_object_handler.rb'
    - 'app/lib/audit/catalog_to_archive.rb'

# Offense count: 3
Metrics/PerceivedComplexity:
  Max: 15

# Offense count: 1
Naming/AccessorMethodName:
  Exclude:
    - 'app/services/moab_validation_handler.rb'

# Offense count: 1
RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/**/*.rb'
    - 'spec/models/preservation_policy_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Exclude:
    - 'app/services/preserved_object_handler.rb'

# Offense count: 4
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/services/preserved_object_handler.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/IfUnlessModifier:
  Exclude:
    - 'spec/services/shared_examples_preserved_object_handler.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, AllowSafeAssignment.
# SupportedStyles: require_parentheses, require_no_parentheses, require_parentheses_when_complex
Style/TernaryParentheses:
  Exclude:
    - 'spec/lib/active_record_utils_spec.rb'
