inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# because this isn't 1994
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/controllers/moab_storage_controller_spec.rb'

RSpec/NamedSubject:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
