inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# --- Metrics ---

Metrics/AbcSize:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # 2 methods but they seem readable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # a method that is simply a case statement

# because this isn't 1994
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/services/preserved_object_handler.rb' # 2 lines 121
    - 'spec/services/preserved_object_handler_spec.rb' # 3 lines are longer

Metrics/MethodLength:
  Max: 20

# --- Rails ---

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # we're using touch on purpose

# --- RSpec ---

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 2

Rspec/MessageSpies:
  Exclude:
    - 'spec/services/preserved_object_handler_spec.rb' # couldn't figure out a logging test

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/services/preserved_object_handler_spec.rb'

# --- Style ---

Style/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

Style/FormatString:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # using interpolated strings

Style/FormatStringToken:
  EnforcedStyle: template # using interpolated strings in PreservedObjectHandler

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop ] isn't a big deal
