language: ruby
rvm:
  - 2.4.2 # make sure this matches our VMs
cache: bundler
services:
  - postgresql
  - redis-server
before_script:
  - bundle exec rake travis_setup_postgres db:reset
bundler_args: "--without 'production development deploy'"
notifications:
  email: false
env:
  global:
  - AWS_REGION=us-west-2
  - secure: o+E4RulzyRQM8Xi7MMgtKuecJb/zKf2Iis5794T5NsRjDyVp3S4i11KEY/sgA5in7sMp4TC+WG2p6AMuH+33t57niUwi6/BFA7Rnt+aNidXpmT9u+IPPzAl/8V1QGMW78hYwl/WNIyblW8Ig7Emjr7me5oCDAH3cECaNM0wAcI1ffo5GWBZK8oPWOfJ6HYX9kM4KW8PwUwdjC5U6kiSpn81uF5iJBVVdYUgCmtwh/Mne0HDBcYr1JIMPntsI3WCiKQpgOhfPHTaPs4YSo2Tmm/O48pfx0bEN760LIdYorBNwNhWNDAmG65ngm/AeC3Fn2nf085HzW6KXfJxPZhEHgKAZC80GTyH93qkevljEeM5lFARh6J4JKB+u22RKIelA79b0J9Pbdp2InJS+lzSBoxAYH1qzCxmXYiRaJuNjBwYRW8pAvgYxMGNhMeI4faxfFgBYaiuwfS3G6cmvgnjnAD1/Cxath/HpvY2P6V2QKh7QSFZdJLu3CNZAz6wZsbQaaVecm1cO0olCV33UNiEtgwHGf+CtK7jrLBdjAIW0RSFm+9ClMniIXYvgZricfIbW/fgG5q3kh+05e2/Dm6jZdKxcX/1kZtGaK7p5uEQISE1/2ldM1+IwjFfJqm6zMKhF5rPNSpo+rJJ8PGbXOmeyPT8LUigpcCAh0kX8hIyUTRA=
  - secure: MJCCFirZOesAm5sc9ztkwswwxIknDcnrLEa/Uqk5HdmM6D41QhN400hl/JubHlMvDylCuSpZEQ3Wa3DRkBvcUdcyq1w8fIVNqn/PENnBJG+IdoiNxjsjf3ifwVkRiSf0dt//dJmjTRMt3yw15gum0kR28vVYU7GpBcqO7xt+a0VRSBKh4bSc6DOvyauqWBx+jtcVFjczXoaRqmgn3peK1RwoaOE//WaIwVgd85JwHQBVNStnSkQt7v8keIrAtsTBvNdZX5CHdBW0ECD5iGf60oTTZ2KvPoBhe8LaNWttpi3ilpyHDVnuVjTyeGZYNsiEmEr46/zdFq0ywNCAtpYTPYcBr//lQ23BEm/NVJuJ8z9efGJM00l/PxxO7PCKOYJyCmO9Vzfw66GU4AuS79M/vCQbfVOX2dB9QJvpSGyypz9jv7nVEbyyiFPgkWB3cfhE7X7+bk6TsqgNpOJMPJKGA2YIYd4jwQ4dPUFZF57XOmbBISowIH9dOFc6niucn1xfSCkWe5Wu6eRc5Pj9R1WPcGeAyjX5CgQgiFCg0EK4PbNCvClCNIj7PkvQm1EJt4OPFvc0AKywM0FfusibrVcFUYOlXaDtLwt5gh/HO1E9fboo8jcGVhjqsNPbyUWjM87WUTJD4xvW48qbGVShtHxSQM4SFm54DSN/2t6zEknLkKA=
