version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:3
    command: redis-server
    ports:
      - 6379:6379
    volumes:
        - redis:/data

volumes:
  redis:
  postgres-data:
