default: &default
  adapter: postgresql
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  user: <%= ENV.fetch("PGUSER", 'postgres') %>
  password: <%= ENV.fetch("PGPASSWORD", 'sekret') %>

production:
  <<: *default
  database: production
  
development:
  <<: *default
  database: development

test:
  <<: *default
  database: test
