endpoint_types:
  online_nfs:
    endpoint_class: online

endpoints:
  # the defaults used when seeding the endpoints that correspond to local storage roots
  storage_root_defaults:
    # value for endpoint_type_name must correspond to an endpoint_types entry (defined above)
    endpoint_type_name: 'online_nfs'
    endpoint_node: 'localhost'
    recovery_cost: 1

moab:
  # this is a list of named storage roots.  the names are used to seed the endpoints table.
  storage_roots:
    # name: '/location/on/disk'  # e.g.
    fixtures: 'spec/fixtures'
  storage_trunk: 'moab_storage_root'

preservation_policies:
  default_policy_name: 'default'
  policy_definitions:
    default:
      archive_ttl: 604_800 # _ttl values are in seconds. 604,800 s == one week.
      fixity_ttl: 604_800

statuses:
  - ok
  - not_found_on_disk
  - expected_version_not_found_on_disk
  - fixity_check_failed
