# the keys of storage_root_map represent deployed hosts and point to their storage_roots
# these host values are just examples or fixtures, for real values, see sul-dlss/shared_configs
storage_root_map:
  default:
    fixture_sr1: 'spec/fixtures/storage_root01'
    fixture_sr2: 'spec/fixtures/storage_root02'
    fixture_sr3: 'spec/fixtures/checksum_root01'
  preservation_catalog_prod:
    fixture_sr1: 'spec/fixtures/storage_root01'
    fixture_sr2: 'spec/fixtures/storage_root02'
    fixture_sr3: 'spec/fixtures/checksum_root01'
  preservation_catalog_prod_a:
    fixture_sr1: 'spec/fixtures/storage_root01'
    fixture_sr2: 'spec/fixtures/storage_root02'
archive_endpoints:
  mock_archive1:
    endpoint_type_name: 'aws_s3'
    endpoint_node: 'localhost'
    storage_location: 'bucket_name'
workflow_services_url: 'https://sul-lyberservices-test.stanford.edu/workflow/'
resque_dashboard_hostnames:
  - 'localhost'
